package com.algocoding.plolymorphismdemo.event;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum DistributedCompensation {

    SINGLE_MONEY_TRANSFER_CREATE,
    SINGLE_MONEY_TRANSFER_DENY,
    SINGLE_MONEY_TRANSFER_CANCEL,
    SINGLE_MONEY_TRANSFER_CONFIRM,

    FUND_CARD_CREATE,
    FUND_CARD_DENY,
    FUND_CARD_CONFIRM,

    BATCH_TRANSFER_CREATE,
    BATCH_TRANSFER_DENY,
    BATCH_TRANSFER_CANCEL,
    BATCH_TRANSFER_CONFIRM,

    BILL_PAYMENT_CREATE,
    BILL_PAYMENT_DENY,
    BILL_PAYMENT_CANCEL,
    BILL_PAYMENT_CONFIRM,

    CURRENCY_TRANSFER_CREATE,
    CURRENCY_TRANSFER_DENY,
    CURRENCY_TRANSFER_CANCEL,
    CURRENCY_TRANSFER_CONFIRM,

    BILL_CREATE,
    BILL_CANCEL,
    BILL_DENY,
    BILL_CONFIRM,

    CURRENCY_TRADE_CREATE,
    CURRENCY_TRADE_DENY,
    CURRENCY_TRADE_CANCEL,
    CURRENCY_TRADE_CONFIRM,

    ITERATIVE_MONEY_TRANSFER_CREATE,
    ITERATIVE_MONEY_TRANSFER_DENY,
    ITERATIVE_MONEY_TRANSFER_CANCEL,
    ITERATIVE_MONEY_TRANSFER_CONFIRM,

    BILL_BATCH_CREATE,
    BILL_BATCH_CANCEL,
    BILL_BATCH_DENY,
    BILL_BATCH_CONFIRM,
}
